# ─────────────────────────────────────────────────────────
# AUTO-GENERATED by policy_compiler.py — DO NOT EDIT BY HAND.
# Source of truth: policies.json
# Policy set: llm-prompt-injection-defence  version: 2.0
# ─────────────────────────────────────────────────────────

package llm.security

import rego.v1

default allow := true

# POL-001 [high] — Block direct authority override originating from user input.
deny contains reason if {
    input.action.source_is_external == false
    input.action.attempts_authority_override == true
    reason := "POL-001: Block direct authority override originating from user input."
}

# POL-002 [critical] — Block indirect authority override where untrusted external content attempts to override the model's instructions. Higher severity than direct override because the user is unaware the manipulation is occurring.
deny contains reason if {
    input.action.source_is_external == true
    input.action.attempts_authority_override == true
    reason := "POL-002: Block indirect authority override where untrusted external content attempts to override the model's instructions. Higher severity than direct override because the user is unaware the manipulation is occurring."
}

# POL-003 [high] — Block any attempt to extract the model's system prompt or internal configuration.
deny contains reason if {
    input.action.attempts_system_extraction == true
    reason := "POL-003: Block any attempt to extract the model's system prompt or internal configuration."
}

# POL-004 [critical] — Block execution attempts that originate from untrusted external content (indirect injection via RAG or documents).
deny contains reason if {
    input.action.source_is_external == true
    input.action.attempts_execution == true
    reason := "POL-004: Block execution attempts that originate from untrusted external content (indirect injection via RAG or documents)."
}

# POL-005 [high] — Block attempts to make the model adopt an unrestricted or unsafe persona.
deny contains reason if {
    input.action.attempts_persona_override == true
    reason := "POL-005: Block attempts to make the model adopt an unrestricted or unsafe persona."
}

# POL-006 [critical] — Block attempts to extract sensitive data such as credentials, API keys, or private information.
deny contains reason if {
    input.action.attempts_sensitive_output == true
    reason := "POL-006: Block attempts to extract sensitive data such as credentials, API keys, or private information."
}

# POL-007 [high] — Block roleplay or task-hijacking attempts that use a legitimate-sounding framing to pivot the model into attacker-controlled behaviour.
deny contains reason if {
    input.action.attempts_roleplay_hijack == true
    reason := "POL-007: Block roleplay or task-hijacking attempts that use a legitimate-sounding framing to pivot the model into attacker-controlled behaviour."
}

# POL-008 [high] — Block context-reset attempts that try to discard prior instructions and inject a fresh attacker-controlled task.
deny contains reason if {
    input.action.attempts_context_reset == true
    reason := "POL-008: Block context-reset attempts that try to discard prior instructions and inject a fresh attacker-controlled task."
}

# POL-009 [high] — Block prompt-leaking attempts that try to make the model echo or print the hidden instructions above the user message.
deny contains reason if {
    input.action.attempts_prompt_leaking == true
    reason := "POL-009: Block prompt-leaking attempts that try to make the model echo or print the hidden instructions above the user message."
}

# POL-010 [medium] — Block any prompt the independent LLM semantic classifier judges unsafe. Acts as a catch-all for novel phrasing that evades the structural signal policies above.
deny contains reason if {
    input.action.llm_judged_unsafe == true
    reason := "POL-010: Block any prompt the independent LLM semantic classifier judges unsafe. Acts as a catch-all for novel phrasing that evades the structural signal policies above."
}

# Final decision: deny overrides the default allow.
allow := false if {
    count(deny) > 0
}
